#!/usr/bin/env bash
# collect_paper1_figures.sh
# Collects all Paper 1 figures into figures-paper-1/ with clean names.
# Upload the contents of figures-paper-1/ as figures/ in Overleaf.
# Re-run this script whenever new figures are generated.

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/figures-paper-1"
FIG="$ROOT/outputs/figures"

mkdir -p "$OUT"

echo "Collecting Paper 1 figures into: $OUT"
echo ""

copy_fig() {
    local src="$1" dst="$2"
    if [ -f "$src" ]; then
        cp "$src" "$OUT/$dst"
        echo "  ✓  $dst"
    else
        echo "  ✗  MISSING: $dst  (expected at $src)"
    fi
}

# ------------------------------------------------------------------
# Main figures (use PDF for vector quality where available, PNG fallback)
# ------------------------------------------------------------------
# Fig 1: quantitative bar chart with bootstrap CIs
copy_fig "$FIG/paper1_fig1.pdf"             "fig1.pdf"
copy_fig "$FIG/paper1_fig1.png"             "fig1.png"

# Fig 2: visual comparison + SR-HR diffmaps (3-row composite)
copy_fig "$FIG/paper1_fig2_composite.png"   "fig2.png"

# Fig 3: multi-resolution frequency analysis (3-row composite)
copy_fig "$FIG/paper1_fig3_composite.png"   "fig3.png"

# Fig 4: hallucination quantification (3-row composite)
copy_fig "$FIG/paper1_fig4_composite.png"   "fig4.png"

# Fig 5: multi-resolution latent embedding (3-row composite)
copy_fig "$FIG/paper1_fig5_composite.png"   "fig5.png"

# Fig 6: statistical (Bland-Altman + Cohen's d forest + violins)
# Use paper1_fig6.png if generated by #106, else fall back to bland_altman_all.png
if [ -f "$FIG/paper1_fig6.png" ]; then
    copy_fig "$FIG/paper1_fig6.png"         "fig6.png"
    copy_fig "$FIG/paper1_fig6.pdf"         "fig6.pdf"
else
    copy_fig "$FIG/bland_altman_all.png"    "fig6.png"
fi

echo ""
echo "Done. Contents of $OUT:"
ls -lh "$OUT"
echo ""
echo "To use in Overleaf:"
echo "  1. Upload the contents of figures-paper-1/ as the 'figures/' folder in your Overleaf project"
echo "  2. In main-v0.tex, reference figures as:  \\includegraphics{figures/fig1}  (or fig1.png)"
